name: build-and-test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn compile
      - run: yarn test
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
          MNEMONIC: ${{ secrets.MNEMONIC }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  format:
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn format

  security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn compile

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo snap install solc
          python -m pip install --upgrade pip
          pip install slither-analyzer==0.8.2 solc-select==0.2.1
      - name: Summary of static ananlysis
        run: |
          slither . --print human-summary
      - name: Contract summary of static ananlysis
        run: |
          slither . --print contract-summary
      - name: Function summary
        run: |
          slither . --print function-summary
      - name: Inheritance
        run: |
          slither . --print inheritance
      - name: Data dependency
        run: |
          slither . --print data-dependency
